blog1/urls.py
from django.urls import path
from . import views

app_name = 'blog1'

urlpatterns=[
    path('',views.post_list, name='post_list'),
]

django_with_react/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='root.html'), name='root'),
    path('', RedirectView.as_view(
        # url='/instagram/'
        pattern_name='instagram:post_list'), name='root'),
    path('admin/', admin.site.urls),
    path('blog1/',include('blog1.urls')),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

instagram/urls.py
from django.urls import path, re_path, register_converter

from . import views


class YearConverter:
    regex = r"20\d{2}"

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return "%04d" % value


register_converter(YearConverter,'year')

app_name = 'instagram'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('new/', views.post_new, name='post_new'),
    path('new/', views.PostCreateView, name='post_new'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    # path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/edit/', views.PostUpdateView, name='post_edit'),
    # path('<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/delete/', views.PostDeleteView, name='post_delete'),
    # path('<int:pk>/', views.PostDetailView),
    # path('archives/<int:year>/', views.archives_year),
    # re_path(r'archives/(?P<year>20\d{2)/', views.archives_year),
    # path('archives/<year:year>/', views.archives_year),
    path('archive/', views.post_archive, name='post_archive'),

]

instagram/models.py
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y%m%d')
    # tag_set = models.ManyToManyField('Tag', blank=True)
    is_public = models.BooleanField(default=False, verbose_name='public')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])


    class Meta:
        ordering = ['-id']

    def message_length(self):
        return len(self.message)
    message_length.short_description = "message length"



class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    pass


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    # post_set = models.ManyToManyField(Post)

    def __str__(self):
        return self.name

instagram/forms.py
from typing import re

import form as form
from django import forms
from django.core.checks import messages

from .models import Post

# class PostForm(forms.Form):
#     title = forms.CharField()
#     content = forms.CharField(widget=form.Textarea)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ['message', 'photo', 'is_public']

    def clean_message(self):
        message = self.cleaned_data.get('message')
        # if messages:
        #     message = re.sub(r'[a-zA-Z]+','',message)
        #     len(message) > 20
        return message

instagram/views.py
from django.core.checks import messages
from django.http import HttpResponse, HttpRequest, Http404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, ArchiveIndexView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm


# def post_new(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return redirect(post)
#     else:
#         form = PostForm()
#     return render(request, 'instagram/post_form.html', {
#         'form': form,
#         'post': None,
#     })


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.objcts.author = self.request.user
        messages.Info(self.request, "Posting saved")
        return super().form_valid(form)


# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#
#     if post.author != request.user:
#         messages.error(request, 'Only owner could modify')
#         return redirect(post)
#
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save()
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)
#     return render(request, 'instagram/post_form.html', {
#         'form': form,
#         'post': post,
#     })


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        messages.Info(self.request, 'Posting modified')
        return super().form_valid(form)

# post_list = ListView.as_view(model=Post, paginate_by=2)

def post_list(request):
    qs = Post.objects.all()
    q = request.GET.get('q','')
    if q:
        qs = qs.filter(message__icontains=q)

    messages.Info(request, 'messages test')

    return render(request, 'instagram/post_list.html', {
        'post_list': qs,
        'q': q,
    })

    # request.POST
    # request.FILES

# def post_detail(request: HttpRequest, pk:int) -> HttpResponse:
#     response = HttpResponse()
#     response.write("Hellow World")
#     return response

# def post_detail(request: HttpRequest, pk:int) -> HttpResponse:
#     post = get_object_or_404(Post, pk=pk)
#     # try:
#     #     post = Post.objects.get(pk=pk)
#     # except Post.DoesNotExist:
#     #     raise Http404
#     return render(request, 'instagram/post_detail.html',{'post':post})

post_detail = DetailView.as_view(
    model=Post,
    )
    # queryset = Post.objects.filter(is_public=True))


# class PostDetailView(DetailView):
#     model = Post
#     # queryset = Post.objects.filter(is_public=True)
#
#     def get_queryset(self):
#         qs = super().get_queryset()
#         if not self.request.user.is_authenticated:
#             qs = qs.filter(is_public=True)
#         return qs

# def archives_year(request, year):
#     return HttpResponse(f"{year}년 archives")


post_archive = ArchiveIndexView.as_view(model=Post, date_field='created_at')


# def post_delete(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     if request.method == 'POST':
#         post.delete()
#         messages.Info(request, 'Posting deleted successfuly')
#         return redirect('instagram:post_list')
#     return render(request, 'instagram/post_confirm_delete.html',{'post':post})


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('instagram:post_list')

    # def get_success_url(self):
    #     return reverse('instagram:post_list')

post_delete = PostDeleteView.as_view()

instagram/templates/instagram/layout.html
{% extends "layout.html" %}

instagram/templates/instagram/post_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>latest</h2>
{{ latest }}
<h2>date_list</h2>
{% for date in date_list %}
    {{ date.year }}
    {{ date|date:"Y" }}
{%  endfor %}
</body>
</html>

instagram/templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}

{% block content %}
    <form action="" method="POST">
        {%  csrf_token %}

        <div class="alert alert-danger">
            Do you want to delete?
        </div>

        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            Check content
        </a>
        <input type="submit" value="delete" class="btn btn-danger"/>
    </form>
{% endblock content %}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block title %}
    <title>Instagram / Post Detail</title>
{% endblock %}

{% block content %}
    <h2>Author: {{ post.author }}</h2>

    {% if post.photo %}
        <div>
            <img src="{{ post.photo.url }}"/>
        </div>
    {% endif %}
    {{  post.message|linebreaks }}

    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        List
    </a>

    <a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-info">
        Edit
    </a>

    <a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">
        Delete
    </a>

{% endblock %}

instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
{#    <table>#}
{#        {{ form.as_table }}#}
{#    </table>#}
    {% buttons %}
        <input type="submit" value="save"/>
    {% endbuttons %}


    <hr/>
    {% if post %}
        <a href="{{ post.instance.get_absolute_url }}">
            content
        </a>
    {% endif %}
        <a href="{% url "instagram:post_list" %}" class="btn btn-primary">List</a>

{% endblock %}

instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block title %}
    <title>Instagram / Post List</title>
{% endblock %}

{% block content %}
    <form action="" method="get">
        <input type="text" name="q" value="{{ q }}" />
        <input type="submit" value="search" />
    </form>

    <a href="{%  url 'instagram:post_new' %}" class="btn btn-primary btn-block mt-3 mb-3">New Post</a>

    <table class="table table-bordered table-hover">
        <tbody>
        {%  for post in post_list %}
            <tr>
                <td>
                    {% if post.photo %}
                        <img src="{{ post.photo.url }}" style="width:100px;"/>
                    {%  else %}
                        No Photo
                    {%  endif %}
                </td>
                <td>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.message }}
                    </a>
                </td>
            </tr>
        {%  endfor %}
        </tbody>
    </table>
    {{ is_paginated }}
    {{ page_obj }}

    {% if is_paginated %}
        {% bootstrap_pagination page_obj size="small" %}
    {%  endif  %}

{% endblock %}